site_name: 回眸
nav:
  - 首页: 'index.md'
  - 用户: 
    - Main: './user/user.md'
  - 回眸: 
    - 首页: './smileback/index.md'    
    - 留言: './smileback/note.md'    
    - 喜欢: './smileback/like.md'    
    - 我的: './smileback/my.md'    
    - 消息: './smileback/im.md'    
    - 举报: './smileback/report.md'    
  
