site_name: 回眸
nav:
  - 首页: 'index.md'
  - 用户: 
    - Main: './user/user.md'
  - 交往: 
    - 通知: './jiaowang/im.md'  
  - 回眸: 
    - 首页: './smileback/index.md'    
    - 留言: './smileback/note.md'    
    - 喜欢: './smileback/like.md'    
    - 我的: './smileback/my.md'    
    - 消息: './smileback/im.md'    
    - 举报: './smileback/report.md'    
    - 封面: './smileback/cover.md'
    - 群组: './smileback/group.md'        
    - Boss: './smileback/boss.md'
    - 小商店: './smileback/store.md'
    - 地址: './smileback/address.md'        
    - 对讲: './smileback/live.md'        
    - 白噪音: './smileback/video.md'
    - 直播: './smileback/talk.md'
    - 共享屏幕: './smileback/screen.md'        
  
